using System.Collections.Immutable;
using System.Text;

namespace Mud.ServiceCodeGenerator;

public abstract class WebApiSourceGenerator : TransitiveCodeGenerator
{
    private readonly string[] HttpClientApiAttributeName = ["HttpClientApiAttribute", "HttpClientApi"];
    protected static readonly string[] SupportedHttpMethods = ["Get", "GetAttribute", "Post", "PostAttribute", "Put", "PutAttribute", "Delete", "DeleteAttribute", "Patch", "PatchAttribute", "Head", "HeadAttribute", "Options", "OptionsAttribute"];

    public override void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 使用自定义方法查找标记了[HttpClientApi]的接口
        var interfaceDeclarations = GetClassDeclarationProvider<InterfaceDeclarationSyntax>(context, HttpClientApiAttributeName);

        // 组合编译和接口声明
        var compilationAndInterfaces = context.CompilationProvider.Combine(interfaceDeclarations);

        // 注册源生成
        context.RegisterSourceOutput(compilationAndInterfaces,
             (spc, source) => Execute(source.Left, source.Right, spc));
    }

    protected abstract void Execute(Compilation compilation, ImmutableArray<InterfaceDeclarationSyntax> interfaces, SourceProductionContext context);

    protected string GetImplementationClassName(string interfaceName)
    {
        if (string.IsNullOrEmpty(interfaceName))
            return "NullOrEmptyInterfaceName";

        return interfaceName.StartsWith("I", StringComparison.Ordinal) && interfaceName.Length > 1 && char.IsUpper(interfaceName[1])
            ? interfaceName.Substring(1)
            : interfaceName + "Impl";
    }

    /// <summary>
    /// 验证接口是否包含有效的HTTP方法
    /// </summary>
    protected bool HasValidHttpMethods(INamedTypeSymbol interfaceSymbol, InterfaceDeclarationSyntax interfaceDecl)
    {
        if (interfaceSymbol == null)
            return false;

        return interfaceSymbol.GetMembers().OfType<IMethodSymbol>()
            .Any(method => method.GetAttributes()
                .Any(attr => SupportedHttpMethods.Contains(attr.AttributeClass?.Name)));
    }

    /// <summary>
    /// 获取HttpClientApi特性
    /// </summary>
    protected AttributeData? GetHttpClientApiAttribute(INamedTypeSymbol interfaceSymbol)
    {
        if (interfaceSymbol == null)
            return null;
        return interfaceSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name is "HttpClientApiAttribute" or "HttpClientApi");
    }

    /// <summary>
    /// 从特性获取基地址
    /// </summary>
    protected string GetBaseUrlFromAttribute(AttributeData attribute)
    {
        if (attribute == null)
            return string.Empty;

        var baseUrlArg = attribute.ConstructorArguments.FirstOrDefault();
        return baseUrlArg.Value?.ToString() ?? string.Empty;
    }

    /// <summary>
    /// 从特性获取超时时间
    /// </summary>
    protected int GetTimeoutFromAttribute(AttributeData attribute)
    {
        if (attribute == null)
            return 100;
        var timeoutArg = attribute.NamedArguments.FirstOrDefault(a => a.Key == "Timeout");
        return timeoutArg.Value.Value is int value ? value : 100; // 默认100秒
    }

    /// <summary>
    /// 生成HttpClient实现类的文件头部
    /// </summary>
    protected void GenerateHttpClientFileHeader(StringBuilder sb, string className, string namespaceName, string interfaceName)
    {

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// 此代码由Mud.ServiceCodeGenerator源生成器自动生成，请勿手动修改");
        sb.AppendLine($"// 生成时间: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");

        var usingNamespaces = GetFileUsingNameSpaces();
        foreach (var usingNamespace in usingNamespaces)
        {
            sb.AppendLine($"using {usingNamespace};");
        }

        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// {interfaceName}的HttpClient实现类");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public partial class {className} : {interfaceName}");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly HttpClient _httpClient;");
        sb.AppendLine($"        private readonly ILogger<{className}> _logger;");
        sb.AppendLine("        private readonly JsonSerializerOptions _jsonSerializerOptions;");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// 构造函数");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <param name=\"httpClient\">HttpClient实例</param>");
        sb.AppendLine("        /// <param name=\"logger\">日志记录器</param>");
        sb.AppendLine($"        public {className}(HttpClient httpClient, ILogger<{className}> logger)");
        sb.AppendLine("        {");
        sb.AppendLine("            _httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));");
        sb.AppendLine("            _logger = logger ?? throw new ArgumentNullException(nameof(logger));");
        sb.AppendLine("            _jsonSerializerOptions = new JsonSerializerOptions");
        sb.AppendLine("            {");
        sb.AppendLine("                PropertyNamingPolicy = JsonNamingPolicy.CamelCase,");
        sb.AppendLine("                WriteIndented = false,");
        sb.AppendLine("                PropertyNameCaseInsensitive = true");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
    }

    /// <summary>
    /// 获取方法参数列表字符串
    /// </summary>
    protected string GetParameterList(IMethodSymbol methodSymbol)
    {
        if (methodSymbol == null)
            return string.Empty;

        return string.Join(", ", methodSymbol.Parameters.Select(p => $"{p.Type} {p.Name}"));
    }
}
